## api-key settings
[api_keys]
# https://fofa.info/api
fofa_key = ""
# https://www.shodan.io/
shodan_key = ""
# https://quake.360.net/quake
quake_key = ""
# https://www.zoomeye.org
zoomeye_key = ""
# https://www.daydaymap.com
daydaymap_key = ""
# https://securitytrails.com
securitytrails_key = ""
# https://hunter.how
hunter_key = ""
# https://hunter.qianxin.com
yt_key = ""
# https://www.virustotal.com
virustotal_key = ""
# https://viewdns.info
viewdns_key = ""
# https://app.binaryedge.io/services/query
binaryedge_key = ""
# https://fullhunt.io/
fullhunt_key = ""
# https://www.whoisxmlapi.com
whoisxmlapi_key = ""
# https://dnsdumpster.com
dnsdump_key = ""
# http://osint.bevigil.com/
bevigil_key = ""
# https://freeapi.robtex.com/
robtex_key = ""
