# 定义url链接中的敏感关键词提取，当包含如下关键词会输出
keywords = ["admin", "login", "system", "administrator", "config", "swagger","forum.php"]
# 定义需要排除的爬取路径文件扩展名
excluded_extensions = [".css", ".woff", ".woff2", ".png", ".jpg", ".jpeg", ".ico", ".gif"]
excluded_patterns = [".css?", ".woff?", ".woff2?", ".png?", ".jpg?", ".jpeg?", ".ico?", ".gif?"]

# 定义域名黑名单 爬取过程中忽略的名单
pass_domain = [
    ".google.com",
    ".baidu.com",
    ".cloudflare.com",
    ".youtube.com",
    ".cloudflare-dns.com",
    ".cloudflaressl.com",
    ".bing.com",
    ".yahoo.com",
    ".amazon.com",
    ".aapanel.com",
    ".qq.com",
    ".weibo.com",
    ".bdstatic.com",
    ".youdao.com",
    ".yahoo.cn",
    ".xunlei.com",
    ".tudou.com",
    ".people.com",
    ".news.cn",
    ".ludashi.com",
    ".alipay.com",
    ".ip138.com",
    ".ips.com",
    ".hao123.com",
    ".google.cn",
    ".google.hk",
    ".google.jp",
    ".facebook.com",
    "openresty.com",
    ".swagger.io",
    ".nginx.com",
    "wordpress.org",
    "cloudflare-dns.com",
    "bootstrapcdn.com",
    ".nosec.org",
    ".alidns.com",
    ".doubleclick.net",
    ".thinkphp.com",
    ".apache.com",
    ".w3.org",
    ".googletagmanager.com",
    ".w.org",
    ".googleapis.com",
    ".googlesyndication.com",
    ".gov.cn",
    ".edu.cn",
    ".360.cn",
    ".microsoft.com",
    ".mozilla.org",
    ".centos.org",
    ".discourse-cdn.com",
    ".taobao.com",
    ".jd.com",
    ".github.com",
]